name: repathcamelyon
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - appdirs=1.4.4
  - attrs=20.3.0
  - backcall=0.2.0
  - black=19.10b0
  - blas=1.0
  - ca-certificates=2020.12.8
  - certifi=2020.12.5
  - click=7.1.2
  - cloudpickle=1.6.0
  - cycler=0.10.0
  - cytoolz=0.11.0
  - dask-core=2.30.0
  - dbus=1.13.6
  - decorator=4.4.2
  - expat=2.2.9
  - flake8=3.8.4
  - fontconfig=2.13.1
  - freetype=2.10.4
  - gettext=0.19.8.1
  - glib=2.66.3
  - gst-plugins-base=1.14.5
  - gstreamer=1.14.5
  - icu=58.2
  - imageio=2.9.0
  - importlib-metadata=2.0.0
  - intel-openmp=2020.2
  - ipykernel=5.3.4
  - ipython=7.16.1
  - ipython_genutils=0.2.0
  - jedi=0.17.2
  - joblib=0.17.0
  - jpeg=9b
  - jupyter_client=6.1.7
  - jupyter_core=4.6.3
  - kiwisolver=1.3.1
  - lcms2=2.11
  - ld_impl_linux-64=2.33.1
  - libedit=3.1.20191231
  - libffi=3.2.1
  - libgcc-ng=9.1.0
  - libgfortran-ng=7.3.0
  - libglib=2.66.3
  - libiconv=1.16
  - libopenblas=0.3.10
  - libpng=1.6.37
  - libsodium=1.0.18
  - libstdcxx-ng=9.1.0
  - libtiff=4.1.0
  - libuuid=2.32.1
  - libxcb=1.13
  - libxml2=2.9.10
  - lz4-c=1.9.2
  - matplotlib=3.3.3
  - matplotlib-base=3.3.3
  - mccabe=0.6.1
  - mkl=2020.2
  - mkl-service=2.3.0
  - mkl_fft=1.2.0
  - mkl_random=1.1.1
  - mypy_extensions=0.4.3
  - ncurses=6.2
  - networkx=2.5
  - numpy=1.19.2
  - numpy-base=1.19.2
  - olefile=0.46
  - openssl=1.1.1i
  - pandas=1.1.3
  - parso=0.7.0
  - pathspec=0.7.0
  - pcre=8.44
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=8.0.0
  - pip=20.2.4
  - prompt-toolkit=3.0.8
  - pthread-stubs=0.4
  - ptyprocess=0.6.0
  - pycodestyle=2.6.0
  - pyflakes=2.2.0
  - pygments=2.7.2
  - pyparsing=2.4.7
  - pyqt=5.9.2
  - python=3.6.9
  - python-dateutil=2.8.1
  - python_abi=3.6
  - pytz=2020.1
  - pywavelets=1.1.1
  - pyyaml=5.3.1
  - pyzmq=19.0.2
  - qt=5.9.7
  - readline=7.0
  - regex=2020.10.15
  - scikit-image=0.17.2
  - scikit-learn=0.23.2
  - scipy=1.5.2
  - setuptools=50.3.1
  - sip=4.19.8
  - six=1.15.0
  - sqlite=3.33.0
  - threadpoolctl=2.1.0
  - tifffile=2020.10.1
  - tk=8.6.10
  - toml=0.10.1
  - toolz=0.11.1
  - tornado=6.0.4
  - traitlets=4.3.3
  - typed-ast=1.4.1
  - typing_extensions=3.7.4.3
  - wcwidth=0.2.5
  - wheel=0.35.1
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xz=5.2.5
  - yaml=0.2.5
  - zeromq=4.3.3
  - zipp=3.4.0
  - zlib=1.2.11
  - zstd=1.4.5
  - pip:
    - absl-py==0.11.0
    - argon2-cffi==20.1.0
    - async-generator==1.10
    - bleach==3.2.1
    - cachetools==4.2.0
    - cffi==1.14.4
    - chardet==3.0.4
    - dataclasses==0.8
    - defusedxml==0.6.0
    - entrypoints==0.3
    - fsspec==0.8.5
    - future==0.18.2
    - google-auth==1.24.0
    - google-auth-oauthlib==0.4.2
    - grpcio==1.34.0
    - idna==2.10
    - jinja2==2.11.2
    - jsonschema==3.2.0
    - jupyter-tensorboard==0.2.0
    - jupyterlab-pygments==0.1.2
    - markdown==3.3.3
    - markupsafe==1.1.1
    - mistune==0.8.4
    - nbclient==0.5.1
    - nbconvert==6.0.7
    - nbformat==5.0.8
    - nest-asyncio==1.4.3
    - notebook==6.1.5
    - oauthlib==3.1.0
    - opencv-python==4.4.0.46
    - openslide-python==1.1.2
    - packaging==20.8
    - pandocfilters==1.4.3
    - prometheus-client==0.9.0
    - protobuf==3.14.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pycparser==2.20
    - pyrsistent==0.17.3
    - pytorch-lightning==1.1.1
    - requests==2.25.0
    - requests-oauthlib==1.3.0
    - rsa==4.6
    - send2trash==1.5.0
    - tensorboard==2.4.0
    - tensorboard-plugin-wit==1.7.0
    - terminado==0.9.1
    - testpath==0.4.4
    - torch==1.7.1
    - torchvision==0.8.2
    - tqdm==4.54.1
    - urllib3==1.26.2
    - webencodings==0.5.1
    - werkzeug==1.0.1
