name: repath
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - appdirs=1.4.4
  - attrs=20.3.0
  - backcall=0.2.0
  - black=19.10b0
  - blas=1.0
  - ca-certificates=2020.12.8
  - certifi=2020.12.5
  - click=7.1.2
  - cloudpickle=1.6.0
  - cycler=0.10.0
  - cytoolz=0.11.0
  - dask-core=2.30.0
  - dbus=1.13.6
  - decorator=4.4.2
  - expat=2.2.9
  - flake8=3.8.4
  - fontconfig=2.13.1
  - freetype=2.10.4
  - gettext=0.19.8.1
  - glib=2.66.3
  - gst-plugins-base=1.14.5
  - gstreamer=1.14.5
  - icu=58.2
  - imageio=2.9.0
  - importlib-metadata=2.0.0
  - intel-openmp=2020.2
  - ipykernel=5.3.4
  - ipython=7.16.1
  - ipython_genutils=0.2.0
  - jedi=0.17.2
  - joblib=0.17.0
  - jpeg=9b
  - jupyter_client=6.1.7
  - jupyter_core=4.6.3
  - kiwisolver=1.3.1
  - lcms2=2.11
  - ld_impl_linux-64=2.33.1
  - libedit=3.1.20191231
  - libffi=3.2.1
  - libgcc-ng=9.1.0
  - libgfortran-ng=7.3.0
  - libglib=2.66.3
  - libiconv=1.16
  - libopenblas=0.3.10
  - libpng=1.6.37
  - libsodium=1.0.18
  - libstdcxx-ng=9.1.0
  - libtiff=4.1.0
  - libuuid=2.32.1
  - libxcb=1.13
  - libxml2=2.9.10
  - lz4-c=1.9.2
  - matplotlib=3.3.3
  - matplotlib-base=3.3.3
  - mccabe=0.6.1
  - mkl=2020.2
  - mkl-service=2.3.0
  - mkl_fft=1.2.0
  - mkl_random=1.1.1
  - mypy_extensions=0.4.3
  - ncurses=6.2
  - networkx=2.5
  - numpy=1.19.2
  - numpy-base=1.19.2
  - olefile=0.46
  - openssl=1.1.1i
  - pandas=1.1.3
  - parso=0.7.0
  - pathspec=0.7.0
  - pcre=8.44
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=8.0.0
  - pip=20.2.4
  - prompt-toolkit=3.0.8
  - pthread-stubs=0.4
  - ptyprocess=0.6.0
  - pycodestyle=2.6.0
  - pyflakes=2.2.0
  - pygments=2.7.2
  - pyparsing=2.4.7
  - pyqt=5.9.2
  - python=3.6.9
  - python-dateutil=2.8.1
  - python_abi=3.6
  - pytz=2020.1
  - pywavelets=1.1.1
  - pyyaml=5.3.1
  - pyzmq=19.0.2
  - qt=5.9.7
  - readline=7.0
  - regex=2020.10.15
  - scikit-image=0.17.2
  - scikit-learn=0.23.2
  - scipy=1.5.2
  - setuptools=50.3.1
  - sip=4.19.8
  - six=1.15.0
  - sqlite=3.33.0
  - threadpoolctl=2.1.0
  - tifffile=2020.10.1
  - tk=8.6.10
  - toml=0.10.1
  - toolz=0.11.1
  - tornado=6.0.4
  - traitlets=4.3.3
  - typed-ast=1.4.1
  - typing_extensions=3.7.4.3
  - wcwidth=0.2.5
  - wheel=0.35.1
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xz=5.2.5
  - yaml=0.2.5
  - zeromq=4.3.3
  - zipp=3.4.0
  - zlib=1.2.11
  - zstd=1.4.5
  - pip:
    - opencv-python==4.4.0.46
    - openslide-python==1.1.2
