name: repath
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _pytorch_select=0.2
  - absl-py=0.11.0
  - attrs=20.3.0
  - blas=1.0
  - blinker=1.4
  - bravado=11.0.2
  - bravado-core=5.17.0
  - brotlipy=0.7.0
  - c-ares=1.17.1
  - ca-certificates=2020.12.8
  - cachetools=2.0.0
  - certifi=2020.12.5
  - cffi=1.14.4
  - chardet=4.0.0
  - click=7.1.2
  - cryptography=3.3.1
  - cudatoolkit=10.0.130
  - cudnn=7.6.5.32
  - freetype=2.10.4
  - fsspec=0.8.5
  - future=0.18.2
  - gitdb=4.0.5
  - gitpython=3.1.11
  - google-auth=1.0.1
  - google-auth-oauthlib=0.4.1
  - grpcio=1.33.2
  - idna=2.10
  - importlib-metadata=3.3.0
  - importlib_metadata=3.3.0
  - intel-openmp=2020.2
  - jpeg=9d
  - jsonref=0.2
  - jsonschema=3.2.0
  - lcms2=2.11
  - ld_impl_linux-64=2.33.1
  - libblas=3.9.0
  - libcblas=3.9.0
  - libedit=3.1.20191231
  - libffi=3.2.1
  - libgcc-ng=9.1.0
  - libgfortran-ng=7.5.0
  - libgfortran4=7.5.0
  - liblapack=3.9.0
  - libopenblas=0.3.12
  - libpng=1.6.37
  - libprotobuf=3.13.0.1
  - libstdcxx-ng=9.1.0
  - libtiff=4.1.0
  - libwebp-base=1.1.0
  - lz4-c=1.9.2
  - markdown=3.3.3
  - mkl=2020.2
  - mkl-service=2.3.0
  - monotonic=1.5
  - msgpack-python=0.5.6
  - ncurses=6.2
  - neptune-client=0.4.129
  - ninja=1.10.2
  - numpy=1.19.4
  - oauthlib=3.0.1
  - olefile=0.46
  - openssl=1.1.1i
  - packaging=20.8
  - pandas=1.0.1
  - pillow=8.0.1
  - pip=20.2.4
  - protobuf=3.13.0.1
  - py3nvml=0.2.5
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.7
  - pycparser=2.20
  - pyjwt=1.7.1
  - pyopenssl=20.0.1
  - pyparsing=2.4.7
  - pyrsistent=0.17.3
  - pysocks=1.7.1
  - python=3.6.9
  - python-dateutil=2.8.1
  - python_abi=3.6
  - pytorch=1.3.1
  - pytorch-lightning=1.1.0
  - pytz=2020.4
  - pyyaml=5.3.1
  - readline=7.0
  - requests=2.25.1
  - requests-oauthlib=1.3.0
  - rsa=3.4.2
  - setuptools=50.3.1
  - simplejson=3.17.2
  - six=1.15.0
  - smmap=3.0.4
  - sqlite=3.33.0
  - swagger-spec-validator=2.7.3
  - tensorboard=2.4.0
  - tensorboard-plugin-wit=1.7.0
  - tk=8.6.10
  - torchvision=0.4.2
  - tqdm=4.54.1
  - typing-extensions=3.7.4.3
  - typing_extensions=3.7.4.3
  - urllib3=1.26.2
  - websocket-client=0.57.0
  - werkzeug=1.0.1
  - wheel=0.35.1
  - xmltodict=0.12.0
  - xz=5.2.5
  - yaml=0.2.5
  - zipp=3.4.0
  - zlib=1.2.11
  - zstd=1.4.5
  - pip:
    - argon2-cffi==20.1.0
    - async-generator==1.10
    - backcall==0.2.0
    - bleach==3.2.1
    - decorator==4.4.2
    - defusedxml==0.6.0
    - entrypoints==0.3
    - ipykernel==5.4.2
    - ipython==7.16.1
    - ipython-genutils==0.2.0
    - jedi==0.17.2
    - jinja2==2.11.2
    - jupyter-client==6.1.7
    - jupyter-core==4.7.0
    - jupyter-tensorboard==0.2.0
    - jupyterlab-pygments==0.1.2
    - markupsafe==1.1.1
    - mistune==0.8.4
    - nbclient==0.5.1
    - nbconvert==6.0.7
    - nbformat==5.0.8
    - nest-asyncio==1.4.3
    - notebook==6.1.5
    - pandocfilters==1.4.3
    - parso==0.7.1
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - prometheus-client==0.9.0
    - prompt-toolkit==3.0.8
    - ptyprocess==0.6.0
    - pygments==2.7.3
    - pyzmq==20.0.0
    - send2trash==1.5.0
    - terminado==0.9.1
    - testpath==0.4.4
    - tornado==6.1
    - traitlets==4.3.3
    - wcwidth==0.2.5
    - webencodings==0.5.1
